Add tests-passed job to workflow
Added a new job to check if tests passed or were skipped after the main test job.

diff --git a/.github/workflows/python-test.yml b/.github/workflows/python-test.yml
--- a/.github/workflows/python-test.yml
+++ b/.github/workflows/python-test.yml
@@ -1,5 +1,4 @@
 name: Test Python Package
-
 on:
   pull_request:
     branches:
@@ -15,12 +14,10 @@ permissions:
 jobs:
   test:
     runs-on: ubuntu-latest
-
     strategy:
       fail-fast: false
       matrix:
         python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
-
     steps:
       - uses: actions/checkout@v4
       - name: Set up Python ${{ matrix.python-version }}
@@ -32,14 +29,26 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
           pip install -r tests/requirements.txt
-
       - name: Run tests
         working-directory: ${{ github.workspace }}
         run: |
           python -m unittest discover -s tests -p 'test_*.py' -t ${{ github.workspace }}
-      
       - name: Run build test
         working-directory: ${{ github.workspace }}
         run: |
           python -m pip install build
           python -m build
+
+  tests-passed:
+    runs-on: ubuntu-latest
+    needs: [test]
+    if: always()
+    steps:
+      - name: All tests passed or skipped
+        run: |
+          if [[ "${{ needs.test.result }}" == "success" || "${{ needs.test.result }}" == "skipped" ]]; then
+            echo "Tests passed or were not required. All good."
+          else
+            echo "Tests failed."
+            exit 1
+          fi
